# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

minimal_mistakes_skin    : "neon"

# Site Settings
locale                   : "en-US"
title_separator          : "-"
title: Sashi Saripalle
email: ""
description: "Machine Learning, Biometrics"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saripalle.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  saripalle
google_analytics: ""

avatar : img/testim.png
author:
  name: sashi saripalle

  bio : "Research | ZOLOZ"
  location : "Kansas City"
  social-network-links:
      email: "sashikanth.s@gmail.com"
      linkedin: "sashi-saripalle-2b6a7462"
      github: "saripalle"

share-links-active:
  email: true
  github: true
  linkedin: true

# Build settings
permalink: none
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock


curriculum:
  - image: img/zoloz.png
    title: ZOLOZ
    info: Current
    description: Research Scientist
    url: http://zoloz.com
  - image: img/ev.png
    title: EyeVerify
    info: 2015-2016
    description: Research Scientist
    url: https://eyevrify.com
  - image: img/ev.png
    title: EyeVerify
    info: 2012-2015
    description: Biometric and Computer Vision Research Intern
    url: http://eyeverify.com


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      social-share: true

  # _pages
  - scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true
